const SUPABASE_URL='https://vihbsfrwnslnmheowkhy.supabase.co';
const SUPABASE_KEY='sb_publishable_RNvbXKwTRLQU5WIYmX0A-g_zokdaYLe';
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const loginBox=document.querySelector('#loginBox'),dashboard=document.querySelector('#dashboard'),loginForm=document.querySelector('#loginForm'),loginMsg=document.querySelector('#loginMsg'),rows=document.querySelector('#rows'),adminMsg=document.querySelector('#adminMsg');
function showMsg(el,text,type=''){el.textContent=text;el.className='form-message '+type;}
async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){loginBox.hidden=false;dashboard.hidden=true;return}const role=(user.app_metadata||{}).role;if(role!=='admin'){await supabase.auth.signOut();showMsg(loginMsg,'This account is not authorized as an admin.','error');return}loginBox.hidden=true;dashboard.hidden=false;const {data,error}=await supabase.from('business_enquiries').select('*').order('created_at',{ascending:false});if(error){showMsg(adminMsg,error.message,'error');return}rows.innerHTML='';for(const x of data){const tr=document.createElement('tr');tr.innerHTML=`<td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(x.name)}</td><td>${esc(x.email)}<br>${esc(x.phone||'')}</td><td>${esc(x.service)}</td><td>${esc(x.message)}</td><td><select data-id="${x.id}" class="status"><option ${x.status==='new'?'selected':''}>new</option><option ${x.status==='contacted'?'selected':''}>contacted</option><option ${x.status==='closed'?'selected':''}>closed</option></select></td>`;rows.appendChild(tr)}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loginForm.addEventListener('submit',async e=>{e.preventDefault();showMsg(loginMsg,'Signing in...');const {error}=await supabase.auth.signInWithPassword({email:email.value,password:password.value});if(error){showMsg(loginMsg,error.message,'error');return}await load()});
rows.addEventListener('change',async e=>{if(!e.target.classList.contains('status'))return;const id=e.target.dataset.id,status=e.target.value;const {error}=await supabase.from('business_enquiries').update({status}).eq('id',id);showMsg(adminMsg,error?error.message:'Status updated.',error?'error':'success')});
logout.addEventListener('click',async()=>{await supabase.auth.signOut();await load()});supabase.auth.onAuthStateChange(()=>load());load();